In [1]:
import numpy as np

In [6]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [7]:
type(array_one)

numpy.ndarray

In [11]:
numbers = [9,8,7,6,]

array_two = np.array(numbers)

array_two

array([9, 8, 7, 6])

In [12]:
array_of_zeros = np.zeros((3,4))

array_of_zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
array_of_zeros = np.zeros((4,3))

array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
array_of_ones = np.ones((3,4))

array_of_ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
array_of_ones_int = np.ones((5,4), dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
Identity Matrics: #An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else

In [24]:
array_eye = np.eye(10)

array_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# Req:Print the even numbers till 100 ------

In [26]:
array_of_evens = np.arange(2,101,2)

array_of_evens

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
x = np.arange(6)

x

array([0, 1, 2, 3, 4, 5])

In [34]:
x.shape

(6,)

In [ ]:
#Req: Change the above 1d array to 2d array



In [35]:
array_nd = x.reshape(2,3)

array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
array_nd.shape

(2, 3)

In [ ]:
# Crating a 2-D array

In [37]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [38]:
array_2d.shape

(2, 3)

In [ ]:
# Crating a 3D array.

In [40]:
c = np.arange(24).reshape(2,3,4)

print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
c.shape

(2, 3, 4)