In [ ]:
#Understanding the Stastical functions in Numpy.

In [2]:
import numpy as np

In [3]:
test_scores = np.array ([30.33,45.67,56.67,67.98,34.76,34.56,75.79])
print(test_scores)

[30.33 45.67 56.67 67.98 34.76 34.56 75.79]


In [5]:
type(test_scores)     # N-dimensional array type called ndarray |It describes the collection of items of the same type. 

numpy.ndarray

In [ ]:
# Req:Calculate the Mean of Test Scores.
      Calculate the median of Test scores.

In [6]:
print('Mean test scores of the students:')
print(np.mean(test_scores))

Mean test scores of the students:
49.39428571428572


In [7]:
print('Median test scores of the students:')
print(np.median(test_scores))

Median test scores of the students:
45.67


In [ ]:
# Working on (salary.csv) date set

In [ ]:
# Req:Bring (salary.csv) to jupyter environment.

# Calulate Mean,Median,standard Deviation,Variance.



In [11]:
x = np.genfromtxt('salary.csv',delimiter=',')

In [12]:
x              #The [ , …, ] (ellipsis)

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [13]:
mean = np.mean(x)
median = np.median(x)
sd = np.std(x)
variance = np.var(x)


In [ ]:
# New ways of Working on f strings.

In [17]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('Standard deviation = %i' %sd)
print('Variance = %i' % variance)



Mean = 55894
Median = 48000
Standard deviation = 55170
Variance = 3043770333


In [ ]:
# Introduction To Iterations:

In [26]:
a = np.arange(12)**2

In [27]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [28]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [29]:
for i in a:
    print(i**(1/4))

0.0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
3.1622776601683795
3.3166247903554


In [ ]:
# Iteration Of a multi-Dimensional Array.

In [40]:
students = np.array([['ashok','neha','diksha','satya'],
                     [45,40,65,75],
                     [80,30,34,95]])

In [41]:
students

array([['ashok', 'neha', 'diksha', 'satya'],
       ['45', '40', '65', '75'],
       ['80', '30', '34', '95']], dtype='<U6')